version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: redmine_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - redmine_network

  redmine:
    build: .
    container_name: redmine_app
    restart: always
    ports:
      - "8080:3000"
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - redmine_files:/usr/src/redmine/files
      - redmine_plugins:/usr/src/redmine/plugins
      - redmine_themes:/usr/src/redmine/public/themes
    depends_on:
      - db
    networks:
      - redmine_network

volumes:
  db_data:
  redmine_files:
  redmine_plugins:
  redmine_themes:

networks:
  redmine_network:
    driver: bridge
